# Generated by Django 4.2.6 on 2023-10-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poketasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokemon_id',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
